[package]
name = "end-rs"
version = "0.1.0"
edition = "2021"

[dependencies]
zbus = {version = "4.3.0", features = ["tokio"]}
zvariant = { version = "4.1.1" }
tokio = {version = "1.38.0", features = ["full"]}
walkdir = {version = "2.5.0"}
